# Generated by Django 4.2.5 on 2023-11-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.CharField(default='p1.png', max_length=500),
            preserve_default=False,
        ),
    ]
