# Generated by Django 4.2.5 on 2023-11-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='slide',
            name='title2',
            field=models.CharField(default='E Commerce.com', max_length=200),
            preserve_default=False,
        ),
    ]
