# Generated by Django 4.2.7 on 2023-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_title_slide_title1_slide_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('testimonial_description', models.CharField(max_length=500)),
                ('user_profile_pic', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
